/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LicensingRouteImport } from './routes/licensing'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BeatsRouteImport } from './routes/beats'
import { Route as IndexRouteImport } from './routes/index'

const LicensingRoute = LicensingRouteImport.update({
  id: '/licensing',
  path: '/licensing',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BeatsRoute = BeatsRouteImport.update({
  id: '/beats',
  path: '/beats',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/beats': typeof BeatsRoute
  '/contact': typeof ContactRoute
  '/licensing': typeof LicensingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beats': typeof BeatsRoute
  '/contact': typeof ContactRoute
  '/licensing': typeof LicensingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/beats': typeof BeatsRoute
  '/contact': typeof ContactRoute
  '/licensing': typeof LicensingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/beats' | '/contact' | '/licensing'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/beats' | '/contact' | '/licensing'
  id: '__root__' | '/' | '/beats' | '/contact' | '/licensing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BeatsRoute: typeof BeatsRoute
  ContactRoute: typeof ContactRoute
  LicensingRoute: typeof LicensingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/licensing': {
      id: '/licensing'
      path: '/licensing'
      fullPath: '/licensing'
      preLoaderRoute: typeof LicensingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beats': {
      id: '/beats'
      path: '/beats'
      fullPath: '/beats'
      preLoaderRoute: typeof BeatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BeatsRoute: BeatsRoute,
  ContactRoute: ContactRoute,
  LicensingRoute: LicensingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
